# The URL the site will be built for
base_url = "https://massle.github.io"

compile_sass = false
minify_html = true
generate_sitemap = false
build_search_index = false

taxonomies = [
    {name = "tags", feed = true, paginate_by = 10},
    {name="year", feed=true, paginate_by=10},
]

title = "Marcel in the Web"
description = "Marcel Steinmetz's personal web page"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

# Extra
[extra]
author = "Marcel Steinmetz"
favicon = "favicon.ico"
list_pages = false
twitter_card = true
enable_search = true

## Navigation
header_nav = [
  { url = "/", name = "/home"},
  { url = "/publications", name = "/publications" },
  { url = "/software", name = "/software" },
]
